命令稿啟動於 2018年03月15日 下午 01:24:40
]0;~
[32muser@DESKTOP-VUB6G4F [33m~[0m
$ whoami; pwd
user
/home/user
]0;~
[32muser@DESKTOP-VUB6G4F [33m~[0m
$ git config -l
user.email=gophs13665@gmail.com
user.name=hpps1106
]0;~
[32muser@DESKTOP-VUB6G4F [33m~[0m
$ git clone https://github.com/<your github account>/lab1.githpp[K[K[K[K[Kit[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.gith/lab1.gitp/lab1.gitp/lab1.gits/lab1.git1/lab1.git1/lab1.git0/lab1.git6/lab1.git
fatal: destination path 'lab1' already exists and is not an empty directory.
]0;~
[32muser@DESKTOP-VUB6G4F [33m~[0m
$ git clone https://github.com/hpps1106/lab1.git
fatal: destination path 'lab1' already exists and is not an empty directory.
]0;~
[32muser@DESKTOP-VUB6G4F [33m~[0m
$ exit

命令稿已於 2018年03月15日 下午 01:28:00
 完成