命令稿啟動於 2018年03月15日 下午 09:30:58
]0;~
[32muser@DESKTOP-VUB6G4F [33m~[0m
$ whoami; pwd
user
/home/user
]0;~
[32muser@DESKTOP-VUB6G4F [33m~[0m
$ git config -l
user.email=gophs13665@gmail.com
user.name=hpps1106
]0;~
[32muser@DESKTOP-VUB6G4F [33m~[0m
$ git clone https://github.com/<your github account>/lab1.git[C[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.gith/lab1.gitp/lab1.gitp/lab1.gits/lab1.git1/lab1.git1/lab1.git0/lab1.git6/lab1.git[C[C[C[C[C[C[C[C[C[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[Kexit

命令稿已於 2018年03月15日 下午 09:32:41
 完成