命令稿啟動於 2018年03月15日 下午 09:58:37
]0;~
[32muser@DESKTOP-VUB6G4F [33m~[0m
$ cd lab1
]0;~/lab1
[32muser@DESKTOP-VUB6G4F [33m~/lab1[0m
$ g++ -o lab1 lab1.cpp
]0;~/lab1
[32muser@DESKTOP-VUB6G4F [33m~/lab1[0m
$ 0/[K[K./lab1
請輸入一個n值 :22
22 11 34 17 52 26 13 40 20 10 5 16 8 4 2 1 
sh: PAUSE：命令找不到
]0;~/lab1
[32muser@DESKTOP-VUB6G4F [33m~/lab1[0m
$ exit

命令稿已於 2018年03月15日 下午 09:59:09
 完成